# 🟥 1ª fase - Planejamento {.unnumbered}

[Esta fase preparatória, dividida em quatro etapas, trata de informações estritamente organizacionais sobre medição de desempenho.]{style="color: gray"}

### 1. Compreender o cenário organizacional de medição de desempenho

A primeira etapa requer a conscientização das condições de medição de desempenho na organização para a qual serão construídos os indicadores, sendo **necessário considerar seu segmento, produtos e serviços, porte (diante da diversidade do setor público) e sua maturidade em relação à medição de desempenho**. Neste último ponto, faz-se necessário a compreensão dos fatores que influenciam esse propósito, como motivações, informações e sistemas disponíveis, contexto e limitações (Gao, 2015; Francischini; Francischini, 2017; Moura *et al*., 2019). Para tanto, pode-se realizar um diagnóstico preliminar institucional (Bahia, 2021; Brasil, 2012); avaliar as restrições existentes para a medição de desempenho (Brasil, 2012; 2018c; 2020b), e certificar-se do grau de suporte e envolvimento da liderança (Brasil, 2020a) e das demais partes interessadas (Brasil, 2010; 2012).

A Subseção 1.4 descreveu a [complexidade do setor público em relação à medição de desempenho](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/~/changes/788/1.-apresentacao/1.4-consequencias-indesejadas-e-limitacoes-da-medicao-de-desempenho#a-complexidade-da-gestao-organizacional-e-do-setor-publico), suas [consequências indesejadas](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/~/changes/788/1.-apresentacao/1.4-consequencias-indesejadas-e-limitacoes-da-medicao-de-desempenho#consequencias-indesejadas-dos-smd-no-setor-publico) e os [fatores limitantes para tal](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/~/changes/788/1.-apresentacao/1.4-consequencias-indesejadas-e-limitacoes-da-medicao-de-desempenho#fatores-limitantes-a-medicao-de-desempenho-no-setor-publico), em que se registra a cultura organizacional como uma barreira à implantação de SMD (Brasil, 2011; Welter; Ensslin, 2022), a participação da liderança (Welter; Ensslin, 2022) e o descompasso que pode existir entre órgãos públicos e a má implementação de sistemas de medição, comprometendo-os (Gonzaga *et al*., 2017; Steccolini; Saliterer; Guthrie, 2020) **justificando essa etapa inicial**.

Ao final da primeira etapa espera-se **o entendimento das condições institucionais que podem catalisar ou dificultar o processo**, o que influenciará nas escolhas seguintes. Organizações com **maturidade na medição de seu desempenho podem estar preparadas para rever seu portfólio de indicadores**, considerando outras dimensões de medição. Por outro lado, aquelas que **ainda não meçam o seu desempenho, podem iniciar com indicadores de dimensões mais simples - especialmente internas à organização** (finanças, insumos, processos) e com pequena quantidade de indicadores, visando a evitar as dificuldades já apresentadas.

### 2. Identificar o objetivo ou missão envolvida na medição

Como os indicadores de desempenho não atuam de forma isolada, mas como elementos de SMD orientados pelo **balanço entre as missões e objetivos das instituições** (conforme as características e necessidades das instituições públicas), **na segunda etapa deve ser definido qual o objetivo ou missão institucional que o indicador em construção busca avaliar, medir e atingir**. Essa informação pode ser registrada por meio do atributo **objetivo ou missão envolvidos**. Com efeito, uma das [consequências indesejadas](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/~/changes/788/1.-apresentacao/1.4-consequencias-indesejadas-e-limitacoes-da-medicao-de-desempenho#consequencias-indesejadas-dos-smd-no-setor-publico) dos SMD é o emprego de objetivos locais limitados, ao invés de objetivos organizacionais (Freeman, 2002) e um [fator limitante](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/~/changes/788/1.-apresentacao/1.4-consequencias-indesejadas-e-limitacoes-da-medicao-de-desempenho#fatores-limitantes-a-medicao-de-desempenho-no-setor-publico) a ser considerado nesta etapa é a diversidade de objetivos a serem medidos, devido a amplitude do setor público (Brasil, 2011; Moura *et al*., 2019).
