# 💡 Fundamentos teóricos
::: {style="text-align: justify;"}
> Esta seção fornece a base teórica necessária ao processo de construção de indicadores de desempenho, desde a contextualização destes em sistemas de medição e gestão até o seu menor detalhamento.

A primeira seção apresentou a medição da performance das instituições do setor público como um dos frutos de um novo modelo de administração pública, com diversos benefícios, porém com restrições e limitações, resultando em efeitos disfuncionais e prejudiciais. Para tanto, é necessário compreender os diversos fatores que envolvem os indicadores de desempenho - desde seu posicionamento na organização até os elementos que os compõem individualmente.

@jackson1993 aponta que **o setor público possui diversas complexidades** (abrangência, objetivos, clientes e partes interessadas) **que precisam ser consideradas e ter reflexo em seus indicadores desempenho**; logo, indicadores triviais e comumente utilizados, provavelmente, não proporcionarão os resultados esperados, especialmente diante das peculiaridades do setor público. Assim, reforça-se a necessidade da construção de uma base teórica prévia ao processo de construção desses indicadores.

Portanto, esta seção inicia-se com o foco mais aberto possível, por meio dos sistemas de medição e gestão de desempenho; segue para a apresentação dos indicadores de desempenho, detalhando-os desde e sua tipologia até os menores elementos que os compõem: os atributos dos indicadores. Por fim, dispõe-se dos critérios de qualidade e validação dos indicadores, os quais contribuem de sobremaneira para a consecução dos benefícios e desvio das limitações dos indicadores citados no início desta introdução.
:::