# Bem-vindo {.unnumbered}
::: {style="text-align: justify;"}

Este guia digital visa dar suporte aos gestores públicos no processo de construção de indicadores de desempenho para suas instituições. Ao gerar informações adequadas e de qualidade, indicadores proporcionam análises e tomada de decisões similares, sendo este um de seus objetivos; todavia, indicadores subdesenvolvidos ou escolhidos erroneamente proporcionaram decisões inadequadas.

Indicadores de desempenho são os mais importantes elementos de um sistema de medição de desempenho organizacional, cuja implementação no setor público é desafiadora pela sua diversidade de objetivos, ampla abrangência e partes interessadas. Por esse motivo, esse guia apresenta suas seções numa sequência própria: inicia-se com os elementos mais amplos e determinantes, gerando a necessária fundamentação teórica até convergir para os indicadores e suas caraterísticas, para, com segurança, apresentar um processo para a sua construção, finalizando com uma aplicação prática.

Portanto, o guia busca ser objetivo e preciso, sem prejuízo da contextualização do tema e do embasamento teórico, valendo-se da interatividade para uma melhor consulta e navegação entre suas seções a fim de se ofertar um guia que faça frente à relevância do tema e às características e necessidades da administração pública.
:::

## O guia para a construção de indicadores de desempenho {.unnumbered}

::: {style="text-align: justify;"}
Este material é o produto de uma dissertação apresentada junto ao [Programa de Pós-Graduação Profissional em Inovação Tecnológica da Universidade Federal de São Paulo](https://www.unifesp.br/campus/sjc/ppgit). Como um guia, ele oferece uma visão geral do tema apresentado, com comentários e, especialmente, instruções para que o leitor possa alcançar o objetivo proposto. Para tanto, dispôs-se de um material inovador em formato digital e com recursos de interação e interatividade, que serão apresentados adiante.

Àqueles que tenham interesse em conhecer o referencial teórico utilizado, as pesquisas realizadas, seus resultados, discussões e forma de validação do guia, podem [acessar integralmente a monografia acadêmica em seu repositório](https://repositorio.unifesp.br/handle/11600/61097) na Universidade Federal de São Paulo. Conforme as referências registradas na monografia, as pesquisas realizadas tiveram como base centenas de estudos, entre eles: artigos científicos, dissertações, teses, livros, guias e manuais provenientes da administração pública brasileira. A todos os seus autores, registra-se aqui o nosso agradecimento, pois seus trabalhos foram essenciais para a construção deste; espera-se que ele também possa ajudar gestores e pesquisadores neste tema tão caro à administração pública.
:::

## Autoria

::: {style="text-align: justify;"}
A responsabilidade e contribuições pela concepção deste guia estão organizadas conforme a [CRediT](https://credit.niso.org/) (Contributor Roles Taxonomy) na seguinte forma:

**Newton Krüger Tallens Junior**: conceitualização, metodologia e escrita (original e revisão).

**Daiana Rafaela Pedersini**: análise formal e validação.

**Ricardo Coser Mergulhão**: análise formal e validação.

**Emerson Gomes dos Santos**: administração do projeto e supervisão
:::

## Plataforma

::: {style="text-align: justify;"}
Este guia foi desenvolvido na linguagem [Quarto](https://quarto.org/) no ambiente [RStudio](https://posit.co/products/open-source/rstudio/) e seus códigos estão abertos e disponíveis na plataforma [Github](https://github.com/).
:::

## Como citar

::: {style="text-align: justify;"}
TALLENS JUNIOR, Newton Krüger; PEDERSINI, Daiana Rafaela; MERGULHÃO, Ricardo Coser; DOS SANTOS, Emerson Gomes. **Guia digital: construção de indicadores de desempenho para órgãos públicos**. [s.l], 2024. *E-book*. Disponível em: https://nktallensjr.github.io/Guia_digital_Q/.
:::

:::