# Planejamento e Elaboração {.unnumbered}

## 1ª fase - Planejamento

### 1. Compreender o cenário organizacional de medição de desempenho

O CBPMESP é responsável pelo \"planejamento, comando, execução, coordenação, fiscalização e controle de todas as atividades de prevenção, extinção de incêndios e de buscas e salvamentos e das atividades técnicas a elas relacionadas no território estadual\", (São Paulo, 1974, art. 39).

Conforme o seu [planejamento estratégico](http://www.ccb.policiamilitar.sp.gov.br/portalcb/_institucional/midias/Planejamento-Estrate%CC%81gico-14DEZ20.pdf) a instituição detém uma força de trabalho, viaturas e embarcações distribuídos em **Estações de Bombeiros**, que são as **instalações físicas de onde equipes de prontidão são acionadas para a prestação de seus serviços**. Essa planejamento estratégico prevê as definições de iniciativas, indicadores de execução, metas e balanceamento das responsabilidades (embora não os apresente). **Depreende-se que existe uma cultura de medição de desempenho nesse órgão**; trata-se de uma instituição militar organizada com base na hierarquia e disciplina (Brasil, 1988, art. 42) cujo papel da liderança parece ser determinante. Conforme a figura abaixo, proveniente do próprio site da instituição na internet, verifica-se o registro dos dados de seus atendimentos:
