# Recursos de interatividade, navegação e avaliação

::: {style="text-align: justify;"}
> Apresenta os recursos de interatividade disponíveis e as formas de navegação pelas páginas do guia.
:::

## Interatividade

::: {style="text-align: justify;"}
Para tornar a consulta e o aprendizado mais dinâmicos e eficientes, o guia utiliza diversas ferramentas, muitas delas comuns, como, **destaques**, [**realces**]{style="background-color:yellow"} e [hyperlinks](index.qmd) (este o levará para a primeira página do guia). Outros exemplos incluem:
:::

## Expansores

::: {.callout collapse="true"}
## 🔽[Clique na seta]{style="color: blue"}

Apresentam um texto explicativo, expandindo o conteúdo do título principal
:::

## Guias

Estruturam o conteúdo de tópicos de um texto

::: panel-tabset
## Guias

Estruturam o conteúdo do texto.

## Avisos

Destacam, reforçam, avisam e alertam.

## Expansores

Apresentam um texto explicativo, desenvolvendo o conteúdo do título principal.
:::

## Avisos

::: callout-tip
## Dica

Destaca uma informação.
:::

::: callout-note
## Nota

Reforça uma informação ou ação.
:::

::: callout-warning
## Importante

Avisa sobe uma informação importante.
:::

::: callout-important
## Alerta

Adverte sobe uma informação crítica.
:::

## Citação

> Citações específicas com destaque no corpo textual do guia.

## Navegação

::: {style="text-align: justify;"}
Todas as seções e capítulos iniciam-se com uma pequena introdução no topo de suas páginas em forma de citação, apresentando suas propostas e objetivos. Nas laterais do guia, há opções e menus de navegação: à esquerda tem-se link para dowload do guia, acesso ao seu código-fonte, um botão para alternar para o modo escuro, outro para o modo de leitura, além de uma barra de busca de palavras. Ainda à esquerda, o menu proporciona a navegação pelas suas seções e capítulos do guia. Já o menu à direita fornece a navegação pelos tópicos existentes na página em leitura. Ao final de cada página, existem botões de navegação para as seções e capítulos anteriores e seguintes.
:::
