# Registro dos resultados do processo

[Esta subseção sintetiza os quadros apresentados ao final de cada fase do processo de construção dos indicadores, compondo a **Registro do Indicador**.]{style="color: gray"}

Os **resultados mais importantes das etapas do processo de construção do indicador devem ser registrados**, especialmente por meio de seus atributos, que são elementos facilitadores desse processo (Uchoa, 2013). Além de registrar aqueles resultados, os atributos também atendem à **necessidade de formalização, registro e catalogação dos indicadores construídos por meio de registros elaborados por esses atributos** (Bahia, 2021; Brasil, 2018c; 2020b; 2023).

Ao final de cada uma das quatro fases apresentadas na subseção anterior, apresentou-se um quadro com os respectivos atributos dos indicadores utilizados; especificamente nas fases de elaboração e definição dos indicadores, sugeriu-se a inclusão dos critérios utilizados para a validação dos indicadores em construção, conforme cada fase. Esses quadros apresentados ao final de cada fase podem ser agrupados, compondo o **Registro do Indicador**:
