# Síntese {.unnumbered}

Nesta seção verificou-se que a **gestão de desempenho organizacional compreende um sistema integrado**, em que as informações coletadas são analisadas, a fim de identificar os fatores que impactam na performance da organização, **subsidiando a tomada de decisões**. Para tanto, é necessário um SMD que **mede, analisa e comunica o desempenho** de atividades, processos, projetos, organizações, programas e políticas públicas **por meio de um conjunto multidimensional de indicadores de desempenho**. No setor público esses SMD devem ter [características específicas](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/2.-fundamentos-teoricos/2.1-sistemas-de-medicao-e-de-gestao-de-desempenho#caracteristicas-dos-sistemas-de-medicao-de-desempenho): a [orientação da medição](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/2.-fundamentos-teoricos/2.1-sistemas-de-medicao-e-de-gestao-de-desempenho#orientacao-de-um-smd-para-orgaos-publicos) pelo **balanço entre as missões e objetivos das suas instituições**,além da **multiplicidade dimensões de desempenho** para capturar as diversas atividades desse setor.

**Dimensões de medição de desempenho** são as diferentes perspectivas consideradas na medição de um objeto; apresentou-se diversas, conforme demanda o setor público, exemplificando algumas [relações entre as elas](/o/AZWDclIWFqqJuBEvyQWk/s/ws6bIBOPv2tLRHdwbB7y/2.-fundamentos-teoricos/2.2-dimensoes-de-medicao-de-desempenho-no-setor-publico#ambientes-algumas-relacoes-entre-as-dimensoes-de-medicao-de-desempenho), pois devem trabalhar em sinergia, para que o resultado de uma dimensão contribua com outra. **Indicadores de desempenho** são parâmetros numéricos de medição que expressam informações qualitativas ou quantitativas sobre o desempenho de um objeto, valorando objetivos, acontecimentos e situações críticas, ou não, para a organização. Os indicadores podem ser classificados: conforme sua posição no nível hierárquico do órgão; as dimensões de desempenho que medem; sua posição na cadeia produtiva e pela especificidade dos indicadores (dividindo-os entre indicadores de esforço e de resultado); essa última é a mais benéfica pela **relação de causa e efeito criada, potencializando o emprego dos indicadores e criando um SMD balanceado.**

Por fim, as últimas subseções apresentaram os **atributos** e os **critérios de validação dos indicadores de desempenho**. Os primeiros adequam os indicadores para a sua função, sendo utilizados na sua construção; são divididos cronologicamente em atributos de elaboração dos indicadores, de definição dos elementos de cálculo e de relato de resultados. Já os critérios de validação, além do uso referente à sua própria denominação, também aferem sua qualidade e são utilizados para a seleção perante uma certa quantidade de indicadores propostos.
