# Síntese {.unnumbered}

O processo proposto para a construção dos indicadores é composto por 14 etapas, agrupadas em quatro fases. A **fase de planejamento busca captar os parâmetros organizacionais de medição de desempenho**, garantindo o alinhamento institucional e o foco dos indicadores pela antecipação do cenário, contexto e fatores críticos para a sua implantação, além do objetivo e objeto de medição (motivo pelo qual destaca-se a Subseção 2.1). Em síntese **é uma fase preliminar e voltada ao órgão público** para o qual serão construídos os indicadores.

A **fase de elaboração dos indicadores possui um viés técnico** sob o ponto de vista da medição de desempenho, em que são aplicados todos conceitos apresentados na Seção 2. A proposta dos indicadores de desempenho ocorre nesta fase, pois já se tem o conhecimento do contexto e objetivos institucionais, do objeto de medição, dos FCS para tal, das dimensões de avaliação desse objeto e dos tipos de indicadores a serem utilizados. Considerando as 14 etapas do processo em tela, **a propositura dos indicadores de desempenho só ocorre na sétima etapa, na metade do processo, tamanha a fundamentação técnica e organizacional necessária para tal**. Nesta fase ocorre a primeira validação dos indicadores em construção e a sua aprovação (ainda que preliminar) junto às partes interessadas - importantes entes para a medição do desempenho, especialmente no setor público.

A **fase de definição é composta por duas importantes etapas**: a primeira busca **garantir que os indicadores tenham objetividade e lastro técnico em relação aos procedimentos de cálculo**, mediante certas definições: a origem e coleta de dados; os cálculos; os níveis de desagregação dos resultados; os parâmetros comparativos e metas; a periodicidade e responsáveis pelas ações citadas. De fato, dados, cálculos e procedimentos errados proporcionarão decisões errôneas para os órgãos que os aplicam. A segunda etapa visa à **aplicação dos critérios de validação**, desta vez, daqueles referentes ao cálculo do indicador; uma vez validados, tem-se os indicadores construídos.

A fase final do processo compreende a **aprovação dos indicadores construídos** mediante a **homologação com a liderança e partes interessadas**, bem como **a seleção dos indicadores, diante de uma grande quantidade de indicadores construídos**. Os resultados das etapas do processo podem ser descritas no **Registro do Indicador** que, além de suportar o processo de construção dos indicadores consignando seus resultados principais por meio de seus atributos e critérios de validação, **atua como um elemento de formalização do indicador construído, concretizando-o e proporcionando sua fácil consulta e divulgação**.
