# Síntese {.unnumbered}
::: {style="text-align: justify;"}
Este capítulo contextualizou **a medição de desempenho organizacional no setor público**, adotada junto com outras práticas de gestão a partir do movimento denominado Nova Gestão Pública*.* **Por meio de sistemas de medição de desempenho, pode-se avaliar a performance de atividades, processos, projetos, organizações, programas e políticas públicas** beneficiando as organizações e a sociedade. A complexidade do setor público, proveniente de suas características ímpares, justificam este e os demais estudos e artefatos similares. Como um guia digital, dispõe-se de recursos de interatividade, tornando a consulta e o aprendizado mais dinâmicos e eficientes.

As implicações positivas da medição de desempenho organizacional no setor público foram descritas em [Objetivos e benefícios da medição de desempenho](objetivos.qmd), em que também constatou-se que **projetar indicadores de desempenho isoladamente, sem considerar características dos sistemas, o contexto de aplicação, formas e partes interessadas, é um erro básico na medição do desempenho organizacional**. Consequentemente, na subseção seguinte, [Limitações dos indicadores e sistemas de medição de desempenho](conseq.qmd), foram apresentadas as consequências não intencionais e os fatores limitantes e barreiras à medição de desempenho no setor público provenientes de pesquisas científicas. Apesar da ênfase daquela subseção nas limitações dos indicadores, **os benefícios gerados pelos indicadores de desempenho e SMD superam suas limitações em intensidade e ganho, tanto para a sociedade quanto para as instituições**.

Após a contextualização do tema (especialmente no setor público) e suas implicações - as quais motivam a elaboração deste guia, a seção seguinte fornece os fundamentos necessários para a construção dos indicadores de desempenho.
:::